import { SAMPLE_IRNS, SAMPLE_SIGNED_QR } from "./gsp-sandbox";
import { fieldsFromExtract, lineItemsFromExtract, newId, type GstInvoice } from "./gst";

const SAMPLES: Array<{
  sourceName: string;
  fields: Parameters<typeof fieldsFromExtract>[0];
  lineItems: Parameters<typeof lineItemsFromExtract>[0];
}> = [
  {
    sourceName: "sample-navkaar-textiles.pdf",
    fields: {
      invoice_number: "NT/2026-27/1842",
      invoice_date: "2026-08-12",
      supplier_name: "Navkaar Textiles Pvt Ltd",
      supplier_gstin: "27AABCU9603R1ZX",
      supplier_address: "18 Kalbadevi Road",
      supplier_place: "Mumbai",
      supplier_pincode: "400002",
      buyer_name: "Westline Retail LLP",
      buyer_gstin: "27AAPFW2194Q1Z3",
      buyer_address: "4th Floor, Westline House, Andheri East",
      buyer_place: "Mumbai",
      buyer_pincode: "400069",
      hsn_sac: "5208, 5210",
      taxable_value: 85000,
      cgst: 2125,
      sgst: 2125,
      igst: 0,
      total_invoice_value: 89250,
      place_of_supply: "Maharashtra (27)",
      irn: SAMPLE_IRNS.navkaar,
      ack_no: "112026081234567",
      ack_date: "2026-08-12 14:22:11",
      signed_qr: SAMPLE_SIGNED_QR.navkaar,
    },
    lineItems: [
      {
        description: "Cotton poplin 60s, dyed, 44 inch",
        hsn_sac: "5208",
        quantity: 420,
        unit: "MTR",
        rate: 125,
        taxable_value: 52500,
        cgst: 1312.5,
        sgst: 1312.5,
        igst: 0,
        line_total: 55125,
      },
      {
        description: "Cotton twill, printed, 58 inch",
        hsn_sac: "5210",
        quantity: 250,
        unit: "MTR",
        rate: 130,
        taxable_value: 32500,
        cgst: 812.5,
        sgst: 812.5,
        igst: 0,
        line_total: 34125,
      },
    ],
  },
  {
    sourceName: "sample-malabar-spices.jpg",
    fields: {
      invoice_number: "MSP-3381",
      invoice_date: "2026-07-28",
      supplier_name: "Malabar Spice Gardens",
      supplier_gstin: "32AALCM4410D1Z2",
      supplier_address: "NH 66, Idukki Road",
      supplier_place: "Kumily",
      supplier_pincode: "685509",
      buyer_name: "Harbour Grocers Pvt Ltd",
      buyer_gstin: "27AADCH8821P1Z8",
      buyer_address: "12 Wadi Bunder",
      buyer_place: "Mumbai",
      buyer_pincode: "400009",
      hsn_sac: "0904, 0908",
      taxable_value: 124000,
      cgst: 0,
      sgst: 0,
      igst: 6200,
      total_invoice_value: 130200,
      place_of_supply: "Maharashtra (27)",
    },
    lineItems: [
      {
        description: "Tellicherry black pepper, grade 1",
        hsn_sac: "0904",
        quantity: 80,
        unit: "KGS",
        rate: 980,
        taxable_value: 78400,
        cgst: 0,
        sgst: 0,
        igst: 3920,
        line_total: 82320,
      },
      {
        description: "Whole cardamom, green, extra bold",
        hsn_sac: "0908",
        quantity: 24,
        unit: "KGS",
        rate: 1900,
        taxable_value: 45600,
        cgst: 0,
        sgst: 0,
        igst: 2280,
        line_total: 47880,
      },
    ],
  },
  {
    sourceName: "sample-lotus-advisory.pdf",
    fields: {
      invoice_number: "LA/INV/0926/077",
      invoice_date: "2026-09-01",
      supplier_name: "Lotus Advisory Services",
      supplier_gstin: "07AAACL1234C1Z5",
      supplier_address: "B-22 Connaught Place",
      supplier_place: "New Delhi",
      supplier_pincode: "110001",
      buyer_name: "Northwind Exports",
      buyer_gstin: "07AAACN5678D1Z1",
      buyer_address: "Okhla Industrial Area",
      buyer_place: "New Delhi",
      buyer_pincode: "110020",
      hsn_sac: "9983",
      taxable_value: 45000,
      cgst: 4050,
      sgst: 4050,
      igst: 0,
      total_invoice_value: 53100,
      place_of_supply: "Delhi (07)",
    },
    lineItems: [
      {
        description: "GST compliance advisory — August 2026",
        hsn_sac: "9983",
        quantity: 1,
        unit: "NOS",
        rate: 45000,
        taxable_value: 45000,
        cgst: 4050,
        sgst: 4050,
        igst: 0,
        line_total: 53100,
      },
    ],
  },
];

export function makeSampleInvoice(index: number): GstInvoice {
  const sample = SAMPLES[index % SAMPLES.length];
  return {
    id: newId(),
    sourceName: sample.sourceName,
    capturedAt: new Date().toISOString(),
    fields: fieldsFromExtract(sample.fields),
    lineItems: lineItemsFromExtract(sample.lineItems),
  };
}
